### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by jasonhildebrand** [jmagnusson/nav-requests#1]
As a python developer with an upcoming NAV integration project, this library looks really interesting and useful.  Thanks for your work on this.

I don't see any documentation.  That's fine.  Do you at least have a couple of simple examples? (i.e. authenticating, fetching a page, making an update and saving?)

**Comment by jacobsvante** [comment]
Hi @jasonhildebrand 

Sorry for late reply. The way I usually use it is by calling it from the terminal. The command `nav` should be available after installing with pip.

First you should create a config to not have to pass in the URL and credentials every time. The default config location is `~/.config/nav.ini`. Should look something like this:

```ini
[prod]
base_url=http://192.168.0.3:7080/DynamicsNAV/WS/My-Company
username=SOMEUSER
password=SOMEPASSWORD

[test]
base_url=http://192.168.0.4:7080/DynamicsNAV/WS/My-Company
username=TESTUSER
password=TESTPASSWORD
```


Then you can make requests as follows.

For example to get the contents of a published Page (done through a page in the UI called something like "Web Services"):

```sh
nav page -c test ShipToAddress
```

This should return results like so:

```xml
<Soap:Envelope xmlns:Soap="http://schemas.xmlsoap.org/soap/envelope/">
  <Soap:Body>
    <ReadMultiple_Result xmlns="urn:microsoft-dynamics-schemas/page/shiptoaddress">
      <ReadMultiple_Result>
        <ShipToAddress>
          <Key>123</Key>
          <Code>123</Code>
          <Name>123</Name>
          <Address_2>123</Address_2>
          <Post_Code>123</Post_Code>
          <City>123</City>
          <Country_Region_Code>123</Country_Region_Code>
          <Location_Code>123</Location_Code>
          <Shipment_Method_Code>123</Shipment_Method_Code>
          <Shipping_Agent_Code>123</Shipping_Agent_Code>
          <Last_Date_Modified>123</Last_Date_Modified>
          <Order_Conf_to_Mail>123</Order_Conf_to_Mail>
          <Customer_No>123</Customer_No>
          <PfsDistribution>123</PfsDistribution>
          <PfsHide_in_Ship_to_List>123</PfsHide_in_Ship_to_List>
        </ShipToAddress>
        <ShipToAddress>
        ...
        </ShipToAddress>
      </ReadMultiple_Result>
    </ReadMultiple_Result>
  </Soap:Body>
</Soap:Envelope>
```

As I'm no big fan of XML and its verbose output I usually add the flag `-j / --json` together with `-r / --results-only`:

```json
[
     {
          "Key": "123",
          "Code": "123",
          "Name": "123",
          "Address_2": "123",
          "Post_Code": "123",
          "City": "123",
          "Country_Region_Code": "123",
          "Location_Code": "123",
          "Shipment_Method_Code": "123",
          "Shipping_Agent_Code": "123",
          "Last_Date_Modified": "123",
          "Order_Conf_to_Mail": "123",
          "Customer_No": "123",
          "PfsDistribution": "123",
          "PfsHide_in_Ship_to_List": "123"
     },
     ...
]
```

For more information on how to use each command just suffix `--help`. In addition to `nav page` you can also use `nav codeunit` and `nav meta`

Some things that you should be aware of:

* The underlying xml library, `xmltodict`, doesn't know what is considered arrays and what is not (I'm not sure if this can be achieved without some type of mapping, as I believe all XML types are user defined). This means that whenever only one item is found in what should be an array, it is returned as an object instead of an array of objects.
  * Perhaps parsing the definition could fix this, haven't looked into it. For above page one would call `nav meta -c test ShipToAddress Page` to get the definition.
* Please note that this lib has only been tested against NAV 2009.


The underlying python code can be used directly as well. Just look at the nav/__main__.py file to see how it's accessed.

Oh, and also, check out [jq](https://stedolan.github.io/jq/), it's perfect when you want to filter and modify the output from this command.

**Comment by jasonhildebrand** [comment]
Wow, thanks for the helpful information!  I've poked around in the code a bit, and have gathered that the library is able to read NAV data, but not add/update records.  Is that correct?

**Comment by jacobsvante** [comment]
Correct 😊

**Comment by jacobsvante** [comment]
@jasonhildebrand I've added support for `CreateMultiple` in v3.0.0, so now you can create data as well. Update is still on the to do list though 😉
